#! /bin/sh

bspc config border_width        2
bspc config window_gap          8
bspc config top_padding        24
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5 

bspc rule -a Gimp desktop=^5 follow=on floating=on
bspc rule -a Chromium desktop=^2

compton --config "$HOME/.config/compton.conf" -b
panel &
