#!/bin/bash

mode=`cat $HOME/.wallpapers/mode`

path=`readlink -f "$HOME/.wallpapers/default"`
case $mode in
  DAY)
    if [[ -z "$1" ]]; then
      tod=`timeofday`
    else
      tod="$1"
    fi
    [[ -e "$HOME/.wallpapers/$tod" ]] || tod=default
    tgt=$(readlink -f "$HOME/.wallpapers/$tod")
    ;;
  RANDOM)
    tgtdir=$(realpath "$HOME/.wallpapers/random-src")
    tgtfiles=($tgtdir/*.*)
    if (( ${#tgtfiles[@]} > 0 )); then
      tgt=${tgtfiles[RANDOM % ${#tgtfiles[@]}]}
    fi
    ;;
esac

feh --bg-fill "$tgt"
